### PR TITLE
Added support for Carbon Mod

### PR DESCRIPTION
**Pull request by ShawnTheShadow**

### CODE REVIEW

**Comment by ich777** [comment]
Thank you for the PR.

I can't accept that PR with your `docker-publish.yml` and `docker-image.yml`

I'm also missing something like that in `start-server.sh` right at line 52:
```
if [ "${OXIDE_MOD}" == "true" ] && [ "${CARBON_MOD}" == "true" ]; then
  echo "Oxide and Carbon mod enabled, you can only enable one at a time, putting containter into sleep mode.
  sleep infinity
fi
```

And I would rather recommend that you put line [148](https://github.com/ich777/docker-steamcmd-server/pull/45/commits/a6ac8764a1e29cc69c131ac09ba5610b1f878bf7#diff-f26647405dcc5f80200c3281af2e813df408014f3155d8504e05d8b7cfa085fdR148) in the newly added if condition for Carbon mod maybe [here](https://github.com/ich777/docker-steamcmd-server/blob/a6ac8764a1e29cc69c131ac09ba5610b1f878bf7/scripts/start-server.sh#L143).

**Comment by ich777** [comment]
Container is already build with your changes.
Thank you!

**Comment by ShawnTheShadow** [comment]
There's probably a better way to show and compare version numbers, but carbon uses "production" as the tag, I'm not so good with regex to do a proper compare with the number in the name.

**Comment by ich777** [comment]
@ShawnTheShadow I just take a quick look into that and that's really stupid what they are doing there since the tag should be the version number, maybe try to create an issue over there in their GitHub since Tags should always be a version number or something unique.

Sure the routine can be changed so that the version number is extracted but I would rather recommend that the fix that on their end...

**Pull request merged**
